name: Twitta il massimo possibile nelle ore giornaliere

on:
  schedule:
    - cron: "0 8-20/2 * * *"   # Twitta ogni 2 ore tra le 08:00 e le 20:00
    - cron: "30 9-19/2 * * *"  # Twitta ogni 2 ore tra le 09:30 e le 19:30
  workflow_dispatch:  # Permette di avviare manualmente il workflow

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Esegui lo script Python
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python main.py
